name: medusa Project

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run build (optional, replace with your build step if needed)
        run: yarn build

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
